# Generated by Django 5.2.5 on 2025-08-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(choices=[('D1', 'Deposito 01'), ('D2', 'Deposito 02'), ('D3', 'Deposito 03')], max_length=50)),
                ('prateleira', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela_afetada', models.CharField(max_length=255)),
                ('id_registro', models.IntegerField()),
                ('acao', models.CharField(max_length=10)),
                ('dados_antigos', models.JSONField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FLAG', 'FLAG'), ('IPL', 'IPL'), ('BOP', 'BOP'), ('OF', 'OF'), ('TCO', 'TCO'), ('MEMO', 'MEMO')], max_length=4)),
                ('numero_caso', models.CharField(max_length=9, unique=True)),
                ('data_requisicao', models.DateField()),
                ('data_recebimento', models.DateField()),
                ('objetivo_pericia', models.TextField()),
                ('status_requisicao', models.CharField(choices=[('ESPERA', 'Em Espera'), ('PROCESSAMENTO', 'Em Processamento'), ('ENTREGUE', 'Entregue'), ('TRANSFERIDO', 'Transferido'), ('DEVOLVIDO', 'Devolvido'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('peso_requisicao', models.CharField(choices=[('P1', 'PESO 01'), ('P2', 'PESO 02'), ('P3', 'PESO 03'), ('P4', 'PESO 04')], max_length=2)),
                ('pae_requisicao', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SMARTPHONE', 'SMARTPHONE'), ('NOTEBOOK', 'NOTEBOOK'), ('PENDRIVE', 'PENDRIVE'), ('HD', 'HD'), ('SSD', 'SSD'), ('CPU', 'CPU'), ('CARTAO MICROSD', 'CARTÃO MICROSD'), ('OUTROS', 'Outros')], max_length=50)),
                ('outros_tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exame', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_UnidadeSolicitante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_armazenamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciamento.armazenamento')),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(max_length=50, unique=True)),
                ('data_entrega_perito', models.DateField()),
                ('perito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciamento.perito')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.requisicao')),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_laudo', models.CharField(max_length=100, unique=True)),
                ('data_entrega_expedicao', models.DateField()),
                ('data_entrega_custodia', models.DateField()),
                ('anexo_digital', models.BooleanField(default=True)),
                ('equipamentos', models.ManyToManyField(to='gerenciamento.equipamento')),
                ('peritos', models.ManyToManyField(to='gerenciamento.perito')),
                ('protocolo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciamento.protocolo')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='protocolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.protocolo'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciamento.solicitante'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.tipoequipamento'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='tipo_exame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerenciamento.tipoexame'),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='unidade_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.unidadesolicitante'),
        ),
    ]
